export const generateOpenApiSpec = (api, report) => {

    // 1. Recursively convert JSON into Swagger properties
    const buildSchema = (obj) => {
        if (typeof obj !== 'object' || obj === null) {
            return { type: typeof obj };
        }
        if (Array.isArray(obj)) {
            return { type: 'array', items: buildSchema(obj[0]) };
        }

        const properties = {};
        for (const key in obj) {
            properties[key] = buildSchema(obj[key]);
        }
        return { type: 'object', properties };
    };

    // 2. Serve the strict OpenAPI 3.0.0 Blueprint
    return {
        openapi: '3.0.0',
        info: {
            title: api.name,
            version: '1.0.0',
            description: `Auto-generated by AI Test Engine. \n\n**Latest Gemini Insight:** ${report.aiInsights}`
        },
        servers: [{ url: new URL(api.url).origin }],
        paths: {
            [new URL(api.url).pathname]: {
                [api.method.toLowerCase()]: {
                    summary: `Execute ${api.name}`,
                    responses: {
                        [report.status]: {
                            description: `Live payload captured safely by worker`,
                            content: {
                                'application/json': {
                                    schema: buildSchema(report.responseData)
                                }
                            }
                        }
                    }
                }
            }
        }
    };
};
